<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Content Remove="C:\Users\Farsica\.nuget\packages\select.pdf.netcore\23.1.0\contentFiles\any\any\Select.Html.dep" />
    <Content Remove="C:\Users\Farsica\.nuget\packages\select.pdf.netcore\23.1.0\contentFiles\any\any\Select.Tools.dep" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="GamaEdtech.Common.DataAnnotation.InjectableAttribute">
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="EntityFrameworkCore.Exceptions.SqlServer" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Handlebars.Net.Helpers.Humanizer" />
    <PackageReference Include="HtmlToOpenXml.dll" />
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" />
    <PackageReference Include="SkiaSharp.QrCode" />
    <PackageReference Include="Spire.Officefor.NETStandard" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Data\GamaEdtech.Data.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Interface\GamaEdtech.Infrastructure.Interface.csproj" />
    <ProjectReference Include="..\Interface\GamaEdtech.Application.Interface.csproj" />
  </ItemGroup>
</Project>
